### ISSUE TITLE
Issue #2 Team Swallows

### ISSUE THREAD

**Issue by abdelp** [Emmanuelaaron/tic-tak-toe#5]
consider using the following code for your validate_wins method:

``` return unless @board[pos_a] == @board[pos_b] && @board[pos_b] == @board[pos_c] && @board[pos_a] != '_' ```

and using an array of all possible winning combinations to check_win

**Comment by Emmanuelaaron** [comment]
Thanks for your feedback. I implemented all the above as you advised
